apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: run-delivery-pipeline
description: hello cloudrun go application pipeline
serialPipeline:
  stages:
  - targetId: run-go-dev
    profiles: [dev]
  - targetId: run-qo-prod
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-go-dev
description: Cloud Run development service
run:
  location: projects/PROJECT_ID/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-go-prod
description: Cloud Run production service
run:
  location: projects/PROJECT_ID/locations/us-central1
