apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-cloudrun-go-dev
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 80224097297-compute@developer.gserviceaccount.com
      containers:
      - image: us-central1-docker.pkg.dev/kwlee-app-eco-sandbox/cloud-run-source-deploy/hello-cloudrun-go/hello-cloudrun-go
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
