apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: run-go-skaffold
profiles:
- name: dev
  manifests:
    rawYaml:
    - run-go-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - run-go-prod.yaml
deploy:
  cloudrun: {}
